services:
  api_26:
    # image: 192.168.10.61:5000/logickee/openbox-android
    build: 
      context: dockerfiles/android
      args:
        ANDROID_API_LEVEL: 26
        SCREEN_RESOLUTION: 1920x1080

    ports:
      - 5901:5900
      - 6081:6080
      - 47231:4723
    volumes:
      - /dev/kvm:/dev/kvm
    privileged: true

  api_25:
    # image: 192.168.10.61:5000/logickee/openbox-android
    build: 
      context: dockerfiles/android
      args:
        ANDROID_API_LEVEL: 25
        SCREEN_RESOLUTION: 1920x1080

    ports:
      - 5900:5900
      - 6080:6080
      - 4723:4723
    volumes:
      - /dev/kvm:/dev/kvm
    privileged: true
