services:
  openbox-android:
    # build: .
    # build: logickee/openbox-android
    # NOTE: internal docker registry
    image: 192.168.10.61:5000/logickee/openbox-android

    ports:
      - 15900:5900
    volumes:
      - /dev/kvm:/dev/kvm
    privileged: true
    