services:
  openbox-android:
    # build: .
    # build: 
    build: 192.168.10.61:5000/logickee/openbox-android
    ports:
      - 15900:5900
    volumes:
      - /dev/kvm:/dev/kvm
    privileged: true
    