FROM openbox-android

# NOTE: setup emulator
# ANDROID SDK root
# pre-request
  # openjdk-17-jdk \

RUN apt install -y git curl wget zip unzip \
  openjdk-8-jdk \
  qemu-system-x86

# NOTE: prevent double define with appium build step
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

RUN mkdir -p /root/Android
# RUN wget -O tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
RUN cd /root/Android && \
  wget -O tools.zip http://192.168.10.61:8181/commandlinetools-linux-8512546_latest.zip && \
  unzip tools.zip && \
  rm tools.zip

ENV ANDROID_HOME $HOME/Android
ENV ANDROID_SDK_ROOT $HOME/Android
ENV ANDROID_USER_HOME $HOME/.android

# ENV PATH $PATH:$ANDROID_HOME/tools
# ENV PATH $PATH:$ANDROID_HOME/tools/bin
ENV PATH $PATH:$ANDROID_HOME/platform-tools
ENV PATH $PATH:$ANDROID_HOME/cmdline-tools/bin

# # NOTE: build-tools for apksigner.apk
RUN yes | sdkmanager --verbose --sdk_root=$ANDROID_HOME --licenses
RUN yes | sdkmanager --verbose --sdk_root=$ANDROID_HOME "build-tools;25.0.0"
RUN yes | sdkmanager --verbose --sdk_root=$ANDROID_HOME "system-images;android-25;default;x86"
RUN yes | sdkmanager --verbose --sdk_root=$ANDROID_HOME "platforms;android-25"

# # # create AVD
RUN echo no | avdmanager -v create avd -f -n test_nexus -k 'system-images;android-25;default;x86' 

# # apksigner.jar
ENV PATH $PATH:$ANDROID_HOME/build-tools/25.0.0/lib

# emulator setup ends here
